version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: ciphershare-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ciphershare
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - cipher-net

  eureka-server:
    build: ./ciphershare-discovery-service
    ports:
      - "8761:8761"
    networks:
      - cipher-net

  user-service:
    build: ./ciphershare-user-service
    ports:
      - "8084:8084"
    networks:
      - cipher-net
    depends_on:
      - eureka-server
      - mysql-db

  file-service:
    build: ./ciphershare-file-service
    ports:
      - "8081:8081"
    networks:
      - cipher-net
    depends_on:
      - eureka-server
      - mysql-db

  audit-service:
    build: ./ciphershare-audit-service
    ports:
      - "8082:8082"
    networks:
      - cipher-net
    depends_on:
      - eureka-server
      - mysql-db

  sharing-service:
    build: ./ciphershare-sharing-service
    ports:
      - "8083:8083"
    networks:
      - cipher-net
    depends_on:
      - eureka-server
      - mysql-db

  api-gateway:
    build: ./ciphershare-api-gateway
    ports:
      - "8080:8080"
    networks:
      - cipher-net
    depends_on:
      - eureka-server
      - user-service
      - file-service
      - audit-service
      - sharing-service

networks:
  cipher-net:
    driver: bridge

volumes:
  mysql-data:
